apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database-dev
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: application-dev
  project: default
  source:
    repoURL: https://github.com/fortranhub/qr-manifests.git
    path: database/
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
